Repository codesquad-members-2025/be-spring-cafe, pull requests merged in 2025-03, with the labels that each got.

#1 [빙빙] step-4 회원 가입 및 목록 조회 기능
  README.md
  build.gradle
  src/main/java/codesquad/codestagram/User.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/resources/application.properties
  src/main/resources/static/css/styles.css
  src/main/resources/templates/footer.html
  src/main/resources/templates/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/register.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step4-1

#2 [BAZZI] - Step1 스프링 카페 - 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/codestagram/controller/BoardController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/dto/UserRequestDto.java
  src/main/java/codesquad/codestagram/dto/UserResponseDto.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/index.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
Labels: Step4-1

#3 [Glad] Step 4 - 1 스프링 카페 - 회원 가입 및 목록 조회 기능
  README.md
  build.gradle
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/domain/user/User.java
  src/main/java/codesquad/codestagram/domain/user/UserController.java
  src/main/resources/application.properties
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/images/80-text.png
  src/main/resources/static/index.html
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/jquery-2.2.0.min.js
  src/main/resources/static/js/scripts.js
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/nav.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step4-1

#4 [JOHNNIE] 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/dto/UserDto.java
  src/main/java/codesquad/codestagram/entity/User.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step4-1

#5 [빙빙] step4-2 글 쓰기 기능 구현
  README.md
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/resources/application.properties
  src/main/resources/static/css/styles.css
  src/main/resources/templates/articles/form.html
  src/main/resources/templates/articles/show.html
  src/main/resources/templates/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: Step4-2

#6 [Glad] Step 4 - 2 스프링 카페 - 글 쓰기 기능 구현
  README.md
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/domain/ViewController.java
  src/main/java/codesquad/codestagram/domain/article/Article.java
  src/main/java/codesquad/codestagram/domain/article/ArticleController.java
  src/main/java/codesquad/codestagram/domain/article/ArticleRepository.java
  src/main/java/codesquad/codestagram/domain/user/User.java
  src/main/java/codesquad/codestagram/domain/user/UserController.java
  src/main/java/codesquad/codestagram/domain/user/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/article/form.html
  src/main/resources/templates/article/view.html
  src/main/resources/templates/index.html
  src/main/resources/templates/nav.html
  src/main/resources/templates/user/edit.html
  src/main/resources/templates/user/profile.html
Labels: Step4-2

#7 [디노] step4-1 스프링 카페 - 회원 가입 및 목록 조회 기능
  README.md
  build.gradle
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/controller/UserForm.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/partials/footer.html
  src/main/resources/templates/partials/head.html
  src/main/resources/templates/partials/nav.html
  src/main/resources/templates/partials/subnav.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/codesquad/codestagram/repository/MemoryUserRepositoryTest.java
  src/test/java/codesquad/codestagram/service/UserServiceTest.java
Labels: Step4-1

#8 [Elbin] step 4-1 스프링 카페 - 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/codestagram/controller/User.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step4-1

#9 [Bazzi] Step2 스프링 카페 - 글 쓰기 기능 구현
  src/main/java/codesquad/codestagram/CodestagramApplication.java
  src/main/java/codesquad/codestagram/controller/BoardController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Board.java
  src/main/java/codesquad/codestagram/domain/Comment.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/dto/BoardRequestDto.java
  src/main/java/codesquad/codestagram/dto/BoardResponseDto.java
  src/main/java/codesquad/codestagram/service/BoardService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/change.html
  src/main/resources/templates/user/index.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
Labels: Step4-2

#10 [MUD] step-4 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layouts/layout.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step4-1

#12 [Glad] Step 4 - 3 DB에 저장하기
  Dockerfile
  README.md
  application.yaml
  build.gradle
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/domain/ViewController.java
  src/main/java/codesquad/codestagram/domain/article/Article.java
  src/main/java/codesquad/codestagram/domain/article/ArticleController.java
  src/main/java/codesquad/codestagram/domain/article/ArticleRepository.java
  src/main/java/codesquad/codestagram/domain/user/User.java
  src/main/java/codesquad/codestagram/domain/user/UserController.java
  src/main/java/codesquad/codestagram/domain/user/UserRepository.java
  src/main/resources/templates/article/form.html
Labels: Step4-3

#13 [JOHNNIE] 스프링 카페 - 글 쓰기 기능 구현
  build.gradle
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/LoginController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/dto/UserDto.java
  src/main/java/codesquad/codestagram/entity/Article.java
  src/main/java/codesquad/codestagram/entity/LoginForm.java
  src/main/java/codesquad/codestagram/entity/User.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/LoginService.java
  src/main/resources/errors.properties
  src/main/resources/templates/home.html
  src/main/resources/templates/login/loginForm.html
  src/main/resources/templates/members/addMemberForm.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile-edit.html
  src/main/resources/templates/user/profile.html
Labels: Step4-2

#15 [디노] step4-2 스프링 카페 - 글 쓰기 기능 구현
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/dto/ArticleForm.java
  src/main/java/codesquad/codestagram/dto/UserForm.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/MemoryArticleRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/update-form.html
  src/test/java/codesquad/codestagram/repository/ArticleRepositoryTest.java
  src/test/java/codesquad/codestagram/repository/UserRepositoryTest.java
  src/test/java/codesquad/codestagram/service/ArticleServiceTest.java
  src/test/java/codesquad/codestagram/service/UserServiceTest.java
Labels: Step4-2

#16 [훈] step4-1 회원 가입 및 목록 조회 기능
  .gitignore
  README.md
  build.gradle
  img.png
  img_1.png
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/user/controller/UserController.java
  src/main/java/codesquad/codestagram/user/domain/User.java
  src/main/java/codesquad/codestagram/user/dto/SignUpRequest.java
  src/main/java/codesquad/codestagram/user/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/UserRepository.java
  src/main/java/codesquad/codestagram/user/service/UserService.java
  src/main/resources/static/images/angry_cloud.jpeg
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/css/bootstrap.min.css
  src/main/resources/templates/css/styles.css
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/codesquad/codestagram/user/repository/MemoryUserRepositoryTest.java
  src/test/java/codesquad/codestagram/user/service/UserServiceTest.java
Labels: Step4-1

#17 [BRIE] Step4-1 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/codestagram/Controller/UserController.java
  src/main/java/codesquad/codestagram/Controller/UserForm.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/subnav.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/codesquad/codestagram/repository/MemoryUserRepositoryTest.java
  src/test/java/codesquad/codestagram/service/UserServiceTest.java
Labels: Step4-1

#20 [Glad] Step 5 - 1 로그인 구현
  README.md
  application.yaml
  src/main/java/codesquad/codestagram/domain/auth/AuthController.java
  src/main/java/codesquad/codestagram/domain/user/User.java
  src/main/java/codesquad/codestagram/domain/user/UserController.java
  src/main/java/codesquad/codestagram/domain/user/UserRepository.java
  src/main/resources/data.sql
  src/main/resources/templates/error.html
  src/main/resources/templates/login.html
  src/main/resources/templates/nav.html
  src/main/resources/templates/user/edit.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/profile.html
Labels: Step5-1

#21 [지토] step-1 스프링 카페 - 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/codestagram/CodestagramApplication.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/navar.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: Step4-1

#24 [빙빙] step5-1 로그인 구현
  README.md
  build.gradle
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/templates/header.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/signIn.html
  src/test/java/codesquad/codestagram/service/UserServiceTest.java
Labels: Step5-1

#25 [MUD] Step-4 글 쓰기 기능 구현
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/MainController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/article/detail.html
  src/main/resources/templates/article/write.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layouts/layout.html
  src/main/resources/templates/main.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/repository/ArticleRepositoryTest.java
  src/test/java/codesquad/codestagram/repository/UserRepositoryTest.java
Labels: Step4-2

#26 [훈] step4-2 스프링 카페 - 글 쓰기 기능 구현
  .editorconfig
  README.md
  src/main/java/codesquad/codestagram/article/controller/ArticleController.java
  src/main/java/codesquad/codestagram/article/domain/Article.java
  src/main/java/codesquad/codestagram/article/dto/ArticleRequest.java
  src/main/java/codesquad/codestagram/article/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/MemoryArticleRepository.java
  src/main/java/codesquad/codestagram/article/service/ArticleService.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/user/controller/UserController.java
  src/main/java/codesquad/codestagram/user/domain/User.java
  src/main/java/codesquad/codestagram/user/dto/UserUpdateRequest.java
  src/main/java/codesquad/codestagram/user/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/UserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/passwordVerifyForm.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/article/repository/MemoryArticleRepositoryTest.java
  src/test/java/codesquad/codestagram/article/service/ArticleServiceTest.java
  src/test/java/codesquad/codestagram/user/repository/MemoryUserRepositoryTest.java
  src/test/java/codesquad/codestagram/user/service/UserServiceTest.java
Labels: Step4-2

#30 [Elbin] step 4-3 스프링 카페 - DB에 저장하기
  build.gradle
  src/main/java/codesquad/codestagram/controller/Article.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/User.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/article/index.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
Labels: Step4-3

#32 [MUD] step-4 DB에 저장하기
  build.gradle
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/MainController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/resources/application.properties
  src/test/java/codesquad/codestagram/repository/ArticleRepositoryTest.java
  src/test/java/codesquad/codestagram/repository/UserRepositoryTest.java
Labels: Step4-3

#34 [케이딘] step4 글 쓰기 기능 구현
  .DS_Store
  .gitignore
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/MainController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/controller/UserForm.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/MemoryArticleRepository.java
  src/main/java/codesquad/codestagram/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
  src/main/resources/static/qna/show.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/updateForm.html
Labels: Step4-2

#36 [디노] step5-1 스프링 카페 4단계 - 로그인 구현
  README.md
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/GlobalModelControllerAdvice.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/exception/ArticleNotFoundException.java
  src/main/java/codesquad/codestagram/exception/DuplicateUserIdException.java
  src/main/java/codesquad/codestagram/exception/InvalidPasswordException.java
  src/main/java/codesquad/codestagram/exception/NotLoggedInException.java
  src/main/java/codesquad/codestagram/exception/UnauthorizedAccessException.java
  src/main/java/codesquad/codestagram/exception/UserNotFoundException.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/partials/error.html
  src/main/resources/templates/partials/nav.html
  src/main/resources/templates/partials/subnav.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/update-form.html
Labels: Step5-1

#35 [빙빙] step 5-2 게시글 권한부여
  README.md
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/AuthController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/dto/ArticleDto.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/articles/edit.html
  src/main/resources/templates/articles/form.html
  src/main/resources/templates/articles/show.html
  src/main/resources/templates/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/test/java/codesquad/codestagram/service/ArticleServiceTest.java
  src/test/java/codesquad/codestagram/service/UserServiceTest.java
Labels: Step5-2

#37 [지토] step-3 스프링 카페 - DB에 저장하기
  README.md
  build.gradle
  src/main/java/codesquad/codestagram/article/controller/ArticleController.java
  src/main/java/codesquad/codestagram/article/domain/Article.java
  src/main/java/codesquad/codestagram/article/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/MemoryArticleRepository.java
  src/main/java/codesquad/codestagram/article/service/ArticleService.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
Labels: Step4-3

#38 Step4-3
  README.md
  build.gradle
  data/springcafe-db.mv.db
  src/main/java/codesquad/codestagram/Controller/UserController.java
  src/main/java/codesquad/codestagram/Controller/UserForm.java
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/domain/Board.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/repository/SDJpaBoardRepository.java
  src/main/java/codesquad/codestagram/repository/SDJpaUserRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/BoardService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/test/java/codesquad/codestagram/service/BoardServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/service/UserServiceIntegrationTest.java
Labels: Step4-3

#39 [훈] step4-3 DB에 저장하기
  README.md
  build.gradle
  img_10.png
  img_11.png
  img_2.png
  img_3.png
  img_4.png
  img_5.png
  img_6.png
  img_7.png
  img_8.png
  img_9.png
  sql/ddl.sql
  src/main/java/codesquad/codestagram/article/controller/ArticleController.java
  src/main/java/codesquad/codestagram/article/domain/Article.java
  src/main/java/codesquad/codestagram/article/dto/ArticleRequest.java
  src/main/java/codesquad/codestagram/article/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/JdbcArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/JdbcTemplateArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/JpaArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/MemoryArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/SpringDataJpaArticleRepository.java
  src/main/java/codesquad/codestagram/article/service/ArticleService.java
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/user/controller/UserController.java
  src/main/java/codesquad/codestagram/user/domain/User.java
  src/main/java/codesquad/codestagram/user/dto/SignUpRequest.java
  src/main/java/codesquad/codestagram/user/dto/UserUpdateRequest.java
  src/main/java/codesquad/codestagram/user/repository/UserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/JdbcTemplateUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/JdbcUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/JpaUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/SpringDataJpaUserRepository.java
  src/main/java/codesquad/codestagram/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/article/service/ArticleServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/user/service/UserServiceIntegrationTest.java
Labels: Step4-3

#40 [디노] step5-2 스프링 카페 5단계 - 게시글 권한부여
  README.md
  src/main/java/codesquad/codestagram/advice/GlobalExceptionHandler.java
  src/main/java/codesquad/codestagram/advice/GlobalModelAttributeAdvice.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/dto/ArticleForm.java
  src/main/java/codesquad/codestagram/interceptor/LoginCheckInterceptor.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/java/codesquad/codestagram/utility/TextUtility.java
  src/main/resources/templates/index.html
  src/main/resources/templates/partials/subnav.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/update-form.html
  src/main/resources/templates/user/list.html
  src/test/java/codesquad/codestagram/service/ArticleServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/service/UserServiceIntegrationTest.java
Labels: Step5-2

#41 [케이딘] step-4 DB에 저장하기
  README.md
  build.gradle
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/MainController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/MemoryArticleRepository.java
  src/main/java/codesquad/codestagram/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/repository/SpringDataJpaArticleRepository.java
  src/main/java/codesquad/codestagram/repository/SpringDataJpaUserRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/ArticleServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/UserServiceIntegrationTest.java
Labels: Step4-3

#42 [Glad] Step 5 - 2 게시글 권한 부여
  README.md
  src/main/java/codesquad/codestagram/common/constants/SessionConstants.java
  src/main/java/codesquad/codestagram/common/exception/GlobalExceptionHandler.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/domain/ViewController.java
  src/main/java/codesquad/codestagram/domain/article/Article.java
  src/main/java/codesquad/codestagram/domain/article/ArticleController.java
  src/main/java/codesquad/codestagram/domain/article/ArticleRepository.java
  src/main/java/codesquad/codestagram/domain/article/ArticleService.java
  src/main/java/codesquad/codestagram/domain/article/exception/ArticleNotFoundException.java
  src/main/java/codesquad/codestagram/domain/auth/AuthController.java
  src/main/java/codesquad/codestagram/domain/auth/exception/UnauthorizedException.java
  src/main/java/codesquad/codestagram/domain/user/UserController.java
  src/main/java/codesquad/codestagram/domain/user/UserRepository.java
  src/main/java/codesquad/codestagram/domain/user/UserService.java
  src/main/java/codesquad/codestagram/domain/user/exception/DuplicatedUserException.java
  src/main/java/codesquad/codestagram/domain/user/exception/UserNotFoundException.java
  src/main/resources/templates/article/edit.html
  src/main/resources/templates/article/view.html
  src/main/resources/templates/error.html
  src/main/resources/templates/index.html
  src/main/resources/templates/nav.html
  src/main/resources/templates/user/form.html
  src/test/java/codesquad/codestagram/domain/article/ArticleServiceTest.java
  src/test/java/codesquad/codestagram/domain/user/UserServiceTest.java
Labels: Step5-2

#43 [지토] step-4 스프링 카페 4단계 - 로그인 구현
  src/main/java/codesquad/codestagram/login/controller/LoginController.java
  src/main/java/codesquad/codestagram/login/service/LoginService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: Step5-1

#44 [MUD] step-5 로그인 구현
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/user/login.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layouts/layout.html
  src/main/resources/templates/main.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/repository/UserRepositoryTest.java
Labels: Step5-1
