Repository codesquad-members-2025/be-spring-cafe, pull requests merged in 2025-04, with the labels that each got.

#50 [케이딘] step-4 로그인 구현
  README.md
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/SpringDataJpaArticleRepository.java
  src/main/java/codesquad/codestagram/repository/SpringDataJpaUserRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/ArticleServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/LoginTest.java
  src/test/java/codesquad/codestagram/UserServiceIntegrationTest.java
Labels: Step5-1

#49 [훈] Step5-1 로그인 구현
  README.md
  sql/ddl.sql
  src/main/java/codesquad/codestagram/article/controller/ArticleController.java
  src/main/java/codesquad/codestagram/article/domain/Article.java
  src/main/java/codesquad/codestagram/article/dto/ArticleRequest.java
  src/main/java/codesquad/codestagram/article/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/JdbcArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/JdbcTemplateArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/JpaArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/MemoryArticleRepository.java
  src/main/java/codesquad/codestagram/article/repository/impl/SpringDataJpaArticleRepository.java
  src/main/java/codesquad/codestagram/article/service/ArticleService.java
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/user/controller/LoginController.java
  src/main/java/codesquad/codestagram/user/controller/UserController.java
  src/main/java/codesquad/codestagram/user/domain/User.java
  src/main/java/codesquad/codestagram/user/dto/LoginRequest.java
  src/main/java/codesquad/codestagram/user/dto/UserUpdateRequest.java
  src/main/java/codesquad/codestagram/user/repository/UserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/JdbcTemplateUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/JdbcUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/JpaUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/user/repository/impl/SpringDataJpaUserRepository.java
  src/main/java/codesquad/codestagram/user/service/SessionService.java
  src/main/java/codesquad/codestagram/user/service/UserService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/passwordVerifyForm.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/article/repository/MemoryArticleRepositoryTest.java
  src/test/java/codesquad/codestagram/article/service/ArticleServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/article/service/ArticleServiceTest.java
  src/test/java/codesquad/codestagram/user/service/UserServiceIntegrationTest.java
Labels: Step5-1

#48 [BRIE] Step5-1 로그인 구현
  README.md
  data/springcafe-db.mv.db
  src/main/java/codesquad/codestagram/Controller/BoardController.java
  src/main/java/codesquad/codestagram/Controller/UserController.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/config/SpringConfig.java
  src/main/java/codesquad/codestagram/dto/BoardForm.java
  src/main/java/codesquad/codestagram/dto/UserForm.java
  src/main/java/codesquad/codestagram/repository/BoardRepository.java
  src/main/java/codesquad/codestagram/repository/MemoryBoardRepository.java
  src/main/java/codesquad/codestagram/repository/MemoryUserRepository.java
  src/main/java/codesquad/codestagram/repository/SDJpaBoardRepository.java
  src/main/java/codesquad/codestagram/repository/SDJpaUserRepository.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/BoardService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/import.sql
  src/main/resources/templates/layout/subnav.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/integration/UserLoginIntegrationTest.java
  src/test/java/codesquad/codestagram/repository/MemoryUserRepositoryTest.java
  src/test/java/codesquad/codestagram/service/BoardServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/service/BoardServiceTest.java
  src/test/java/codesquad/codestagram/service/UserServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/service/UserServiceTest.java
Labels: Step5-1

#46 [Glad] Step 5 - 3 댓글
  README.md
  application.yaml
  deploy.sh
  src/main/java/codesquad/codestagram/common/exception/GlobalExceptionHandler.java
  src/main/java/codesquad/codestagram/common/interceptor/LoginCheckInterceptor.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/domain/ViewController.java
  src/main/java/codesquad/codestagram/domain/article/Article.java
  src/main/java/codesquad/codestagram/domain/article/ArticleController.java
  src/main/java/codesquad/codestagram/domain/article/ArticleRepository.java
  src/main/java/codesquad/codestagram/domain/article/ArticleService.java
  src/main/java/codesquad/codestagram/domain/reply/Reply.java
  src/main/java/codesquad/codestagram/domain/reply/ReplyController.java
  src/main/java/codesquad/codestagram/domain/reply/ReplyRepository.java
  src/main/java/codesquad/codestagram/domain/reply/ReplyService.java
  src/main/java/codesquad/codestagram/domain/reply/exception/ReplyNotFoundException.java
  src/main/java/codesquad/codestagram/domain/user/UserService.java
  src/main/resources/data.sql
  src/main/resources/templates/article/view.html
  src/main/resources/templates/nav.html
Labels: Step5-3

#47 [빙빙] step5-3 스프링 카페 6단계 - 댓글
  README.md
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/AuthController.java
  src/main/java/codesquad/codestagram/controller/ReplyController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/Reply.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/ReplyRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/AuthService.java
  src/main/java/codesquad/codestagram/service/ReplyService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/articles/show.html
  src/main/resources/templates/header.html
  src/test/java/codesquad/codestagram/controller/ArticleControllerTest.java
  src/test/java/codesquad/codestagram/controller/AuthControllerTest.java
  src/test/java/codesquad/codestagram/controller/ReplyControllerTest.java
  src/test/java/codesquad/codestagram/controller/UserControllerTest.java
  src/test/java/codesquad/codestagram/service/ArticleIntegrationTest.java
  src/test/java/codesquad/codestagram/service/ArticleServiceTest.java
  src/test/java/codesquad/codestagram/service/AuthServiceTest.java
  src/test/java/codesquad/codestagram/service/ReplyIntegrationTest.java
  src/test/java/codesquad/codestagram/service/ReplyServiceTest.java
  src/test/java/codesquad/codestagram/service/UserServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/service/UserServiceTest.java
Labels: Step5-3

#51 [JOHNNIE] - 스프링 카페 6단계 - 댓글
  build.gradle
  src/main/java/codesquad/codestagram/CodestagramApplication.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/CommentController.java
  src/main/java/codesquad/codestagram/controller/LoginController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/BaseEntity.java
  src/main/java/codesquad/codestagram/domain/Comment.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/dto/request/CommentWriteRequest.java
  src/main/java/codesquad/codestagram/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/repository/CommentRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/CommentService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/delete-confirmation.html
  src/main/resources/templates/user/profile.html
Labels: Step5-3

#53 [훈] step5-2 게시글 권한 부여
  README.md
  src/main/java/codesquad/codestagram/article/controller/ArticleController.java
  src/main/java/codesquad/codestagram/article/domain/Article.java
  src/main/java/codesquad/codestagram/article/dto/ArticleRequest.java
  src/main/java/codesquad/codestagram/article/service/ArticleService.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/user/controller/LoginController.java
  src/main/java/codesquad/codestagram/user/controller/UserController.java
  src/main/java/codesquad/codestagram/user/domain/User.java
  src/main/java/codesquad/codestagram/user/dto/UserUpdateRequest.java
  src/main/java/codesquad/codestagram/user/service/SessionService.java
  src/main/java/codesquad/codestagram/user/service/UserService.java
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/updateForm.html
  src/main/resources/templates/user/list.html
Labels: Step5-2

#55 [Glad] Step 6 - 1 스프링 카페 7단계 - ajax 댓글 구현
  application.yaml
  build.gradle
  deploy.sh
  src/main/java/codesquad/codestagram/domain/article/ArticleController.java
  src/main/java/codesquad/codestagram/domain/reply/ReplyController.java
  src/main/java/codesquad/codestagram/domain/reply/dto/ReplyRequestDto.java
  src/main/java/codesquad/codestagram/domain/reply/dto/ReplyResponseDto.java
  src/main/resources/templates/article/view.html
Labels: Step6-1

#56 [케이딘] step5-2 게시글 권한부여
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/GlobalExceptionHandler.java
  src/main/java/codesquad/codestagram/controller/MainController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/exception/UserNotFoundException.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/resources/templates/error/general-error.html
  src/main/resources/templates/error/no-found.html
  src/main/resources/templates/error/null-pointer.html
  src/main/resources/templates/error/user-not-found.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/list.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/profile.html
Labels: Step5-2

#57 [MUD] step-5 권한 부여
  .gitignore
  src/main/java/codesquad/codestagram/config/AppConstants.java
  src/main/java/codesquad/codestagram/config/LogInterceptor.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/controller/ArticleController.java
  src/main/java/codesquad/codestagram/controller/UserController.java
  src/main/java/codesquad/codestagram/domain/Article.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/repository/UserRepository.java
  src/main/java/codesquad/codestagram/service/ArticleService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/css/styles.css
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/templates/article/detail.html
  src/main/resources/templates/article/updateForm.html
  src/main/resources/templates/article/write.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layouts/layout.html
  src/main/resources/templates/main.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/updateForm.html
Labels: Step5-2

#58 [빙빙] step6-1 ajax 댓글 구현
  README.md
  build.gradle
  src/main/java/codesquad/codestagram/controller/ReplyApiController.java
  src/main/java/codesquad/codestagram/dto/ReplyDto.java
  src/main/java/codesquad/codestagram/service/ReplyService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/templates/articles/show.html
  src/test/java/codesquad/codestagram/controller/ReplyApiControllerTest.java
Labels: Step6-1

#59 [BRIE] Step5-2 게시글 권한 부여
  README.md
  data/springcafe-db.mv.db
  src/main/java/codesquad/codestagram/Controller/BoardController.java
  src/main/java/codesquad/codestagram/Controller/UserController.java
  src/main/java/codesquad/codestagram/config/MvcConfig.java
  src/main/java/codesquad/codestagram/domain/Board.java
  src/main/java/codesquad/codestagram/domain/User.java
  src/main/java/codesquad/codestagram/dto/BoardForm.java
  src/main/java/codesquad/codestagram/dto/UserForm.java
  src/main/java/codesquad/codestagram/exception/GlobalExceptionHandler.java
  src/main/java/codesquad/codestagram/repository/BoardRepository.java
  src/main/java/codesquad/codestagram/service/BoardService.java
  src/main/java/codesquad/codestagram/service/UserService.java
  src/main/java/codesquad/codestagram/util/AuthUtil.java
  src/main/resources/application.properties
  src/main/resources/import.sql
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/qna/edit.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/codestagram/integration/BoardIntegrationTest.java
  src/test/java/codesquad/codestagram/integration/UserLoginIntegrationTest.java
  src/test/java/codesquad/codestagram/service/BoardServiceIntegrationTest.java
  src/test/java/codesquad/codestagram/service/UserServiceIntegrationTest.java
Labels: Step5-2

#63 [Glad] Step 6-2 8단계 페이징 구현하기
  README.md
  application.yaml
  deploy.sh
  env_setup.sh
  src/main/java/codesquad/codestagram/CodestagramApplication.java
  src/main/java/codesquad/codestagram/common/constants/PaginationConstants.java
  src/main/java/codesquad/codestagram/common/entity/BaseEntity.java
  src/main/java/codesquad/codestagram/common/exception/GlobalExceptionHandler.java
  src/main/java/codesquad/codestagram/domain/ViewController.java
  src/main/java/codesquad/codestagram/domain/article/Article.java
  src/main/java/codesquad/codestagram/domain/article/ArticleController.java
  src/main/java/codesquad/codestagram/domain/article/ArticleRepository.java
  src/main/java/codesquad/codestagram/domain/article/ArticleService.java
  src/main/java/codesquad/codestagram/domain/reply/Reply.java
  src/main/java/codesquad/codestagram/domain/reply/ReplyController.java
  src/main/java/codesquad/codestagram/domain/reply/ReplyRepository.java
  src/main/java/codesquad/codestagram/domain/reply/ReplyService.java
  src/main/java/codesquad/codestagram/domain/reply/dto/ReplyResponseDto.java
  src/main/resources/templates/article/view.html
  src/main/resources/templates/index.html
  src/test/java/codesquad/codestagram/domain/article/ArticleServiceTest.java
  src/test/java/codesquad/codestagram/domain/reply/ReplyServiceTest.java
Labels: Step6-2

#64 [훈] step5-3 스프링 카페 6단계 - 댓글
  .gitignore
  README.md
  img_12.png
  img_13.png
  img_14.png
  img_15.png
  img_16.png
  img_17.png
  img_18.png
  img_19.png
  img_20.png
  img_21.png
  img_22.png
  img_23.png
  src/main/java/codesquad/codestagram/article/controller/ArticleController.java
  src/main/java/codesquad/codestagram/article/domain/Article.java
  src/main/java/codesquad/codestagram/article/repository/ArticleRepository.java
  src/main/java/codesquad/codestagram/article/service/ArticleService.java
  src/main/java/codesquad/codestagram/common/config/MvcConfig.java
  src/main/java/codesquad/codestagram/common/exception/GlobalExceptionHandler.java
  src/main/java/codesquad/codestagram/common/exception/dto/ErrorResponse.java
  src/main/java/codesquad/codestagram/common/exception/error/BaseException.java
  src/main/java/codesquad/codestagram/common/exception/error/DuplicateResourceException.java
  src/main/java/codesquad/codestagram/common/exception/error/ForbiddenException.java
  src/main/java/codesquad/codestagram/common/exception/error/InvalidRequestException.java
  src/main/java/codesquad/codestagram/common/exception/error/ResourceNotFoundException.java
  src/main/java/codesquad/codestagram/common/exception/error/UnauthorizedException.java
  src/main/java/codesquad/codestagram/reply/controller/ReplyController.java
  src/main/java/codesquad/codestagram/reply/domain/Reply.java
  src/main/java/codesquad/codestagram/reply/dto/ReplyRequest.java
  src/main/java/codesquad/codestagram/reply/repository/ReplyRepository.java
  src/main/java/codesquad/codestagram/reply/service/ReplyService.java
  src/main/java/codesquad/codestagram/user/controller/LoginController.java
  src/main/java/codesquad/codestagram/user/controller/UserController.java
  src/main/java/codesquad/codestagram/user/domain/User.java
  src/main/java/codesquad/codestagram/user/service/SessionService.java
  src/main/java/codesquad/codestagram/user/service/UserService.java
  src/main/resources/application.yaml
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/login.html
Labels: Step5-3
